# Generated by Django 5.1.6 on 2025-05-15 11:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppUtility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Currency", "CURRENCY"),
                            ("Library Opening Hours", "LIBRARY_OPENING_HOURS"),
                            ("Library Closing Hours", "LIBRARY_CLOSING_HOURS"),
                            ("Books borrowing limit", "BOOKS_BORROWING_LIMIT"),
                        ],
                        help_text="Name of this utility",
                        max_length=30,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Description of this app utility",
                        verbose_name="Description",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Value for this utility",
                        max_length=100,
                        verbose_name="Value",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the entry was updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the entry was created",
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Utility",
                "verbose_name_plural": "App Utilities",
            },
        ),
        migrations.CreateModel(
            name="Concern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about",
                    models.CharField(
                        help_text="Main issue being raised.",
                        max_length=200,
                        verbose_name="About",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        help_text="Concern in details", verbose_name="Details"
                    ),
                ),
                (
                    "response",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Feedback from the concerned body",
                        null=True,
                        verbose_name="Response",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "OPEN"),
                            ("In Progress", "IN_PROGRESS"),
                            ("Resolved", "RESOLVED"),
                            ("Closed", "CLOSED"),
                        ],
                        default="Open",
                        help_text="Current status of the concern",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the entry was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the entry was created",
                        verbose_name="Created At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Concern",
                "verbose_name_plural": "Member Concerns",
            },
        ),
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("General", "GENERAL"),
                            ("Payment", "PAYMENT"),
                            ("Maintenance", "MAINTENANCE"),
                            ("Promotion", "PROMOTION"),
                            ("Warning", "WARNING"),
                            ("Other", "OTHER"),
                        ],
                        default="General",
                        help_text="Category of the message",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Message subject",
                        max_length=200,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        help_text="Message in details", verbose_name="Content"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the message was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the message was last updated",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Message",
                "verbose_name_plural": "Group Messages",
            },
        ),
        migrations.CreateModel(
            name="MemberGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the members' group",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Description of the user group",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "social_media_link",
                    models.URLField(
                        blank=True,
                        help_text="Link to online forum for members",
                        null=True,
                        verbose_name="Social media link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Group",
                "verbose_name_plural": "Member Groups",
            },
        ),
        migrations.CreateModel(
            name="PersonalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("General", "GENERAL"),
                            ("Payment", "PAYMENT"),
                            ("Maintenance", "MAINTENANCE"),
                            ("Promotion", "PROMOTION"),
                            ("Warning", "WARNING"),
                            ("Other", "OTHER"),
                        ],
                        default="General",
                        help_text="Category of the message",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Message subject",
                        max_length=200,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        help_text="Message in details", verbose_name="Content"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Message read status",
                        verbose_name="Is read",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the entry was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the entry was last updated",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Message",
                "verbose_name_plural": "Personal Messages",
            },
        ),
    ]
