# Generated by Django 5.1.6 on 2025-05-15 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="concern",
            name="user",
            field=models.ForeignKey(
                help_text="Person raising this concern",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concerns",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="read_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have read this message",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Read by",
            ),
        ),
        migrations.AddField(
            model_name="membergroup",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who are members of this group",
                related_name="member_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Members",
            ),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="groups",
            field=models.ManyToManyField(
                help_text="User-Groups to receive this message",
                related_name="group_messages",
                to="management.membergroup",
                verbose_name="Groups",
            ),
        ),
        migrations.AddField(
            model_name="personalmessage",
            name="user",
            field=models.ForeignKey(
                help_text="Receiver of the message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
