# Generated by Django 5.1.6 on 2025-05-15 11:32

import project.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Account name e.g M-PESA", max_length=50
                    ),
                ),
                (
                    "paybill_number",
                    models.CharField(
                        help_text="Paybill number e.g 247247", max_length=100
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        default="%(username)s",
                        help_text="Any or combination of %(id)d, %(username)s,%(phone_number)s, %(email)s etc",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Account active status"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Information related to this account.",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the entry was updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the entry was created",
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Account Details",
            },
        ),
        migrations.CreateModel(
            name="ExtraFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Lost book penalty", "LOST_BOOK_PENALTY"),
                            ("Late book return penalty", "LATE_BOOK_RETURN_PENALTY"),
                        ],
                        help_text="Fee name",
                        max_length=100,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                ("details", models.TextField(help_text="What is this fee for?")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Fee amount in Ksh", max_digits=8
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the entry was updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the entry was created",
                        verbose_name="created at",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Deposit", "DEPOSIT"),
                            ("Payment", "PAYMENT"),
                            ("Refund", "REFUND"),
                        ],
                        help_text="Transaction type",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount in Ksh",
                        max_digits=10,
                    ),
                ),
                (
                    "means",
                    models.CharField(
                        choices=[
                            ("Cash", "CASH"),
                            ("M-PESA", "MPESA"),
                            ("Bank", "BANK"),
                            ("Other", "OTHER"),
                        ],
                        default="M-PESA",
                        help_text="Select means of transaction",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=project.utils.generate_random_token,
                        help_text="Transaction ID or -- for cash.",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Further transaction details",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the entry was created",
                        verbose_name="created at",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Account balance",
                        max_digits=8,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the entry was updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the entry was created",
                        verbose_name="created at",
                    ),
                ),
            ],
        ),
    ]
